version: "3.4"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./static:/my_blog_django/static
      - ./media:/my_blog_django/media
    depends_on:
      - db
      - my_blog_django
    networks:
      - combined-network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: applications_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - combined-network

  my_blog_django:
    build: ./my_blog_django
    container_name: my_blog_django
    volumes:
      - ./static:/my_blog_django/static
      - ./media:/my_blog_django/media
    depends_on:
      - db
    networks:
      - combined-network

networks:
  combined-network:
    driver: bridge